--- 
- hosts: 172.31.25.227
  become: yes
  tasks:
  - include-tasks: myfile.yml
  - name: copy static file into ansible nodes
    copy:
      src: mytestfile
      dest: /home/ubuntu/mystaticfile
  - name: install webserver
    apt:
      name: apache2
      state: present
    