---
- hosts: all
  become: yes
  tasks:
  - name: git
    apt:
      name: git
      state: present
    tags: mygit

  - name: tree
    apt:
      name: tree
      state: present
    tags: mytree  

  - name: wget
    apt:
      name: wget
      state: present
    tags: mywget

