--- 
- hosts: all
  become: yes
  tasks:
    - name: install webserver on RedHat ansible nodes
      yum: 
        name: httpd
        state: present
      when: ansible_os_family =="RedHat"
    - name: start webserver on RedHat ansible nodes
      services:
         name: httpd
         state: started
      when: ansible_os_family =="RedHat"
  
  